FROM golang:1.26-alpine3.24 AS build

RUN apk add --no-cache git

WORKDIR /src
COPY . .

RUN go generate ./... && \
    CGO_ENABLED=0 go build -trimpath -o /mediamtx .

FROM alpine:3.22

RUN apk add --no-cache ca-certificates

COPY --from=build /mediamtx /mediamtx
COPY mediamtx.yml /mediamtx.yml

ENTRYPOINT ["/mediamtx"]
